feature/REL 985/application cache warmup after instance refresh
oat-sa/extension-tao-funcacl pull request #114
Opened 2023-06-21 16:42 UTC by vbyndych

develop

2023-06-22 09:59 UTC, vbyndych commented
Main PR: [#1051](https://github.com/oat-sa/generis/pull/1051)

2023-06-22 14:19 UTC, augustas requested changes
Looking good. A note for later, when generis PR will be merged and released to have a version, this PR should get a bump in `composer.json` dependencies for `generis`, so that `CacheWarmupEvent` would exist

2023-06-22 14:19 UTC, augustas commented on migrations/Version202306211554491526_funcAcl.php
> +final class Version202306211554491526_funcAcl extends AbstractMigration
Likewise to https://github.com/oat-sa/tao-core/pull/3842, an install script is needed to register event listeners as well

2023-06-27 15:28 UTC, yaraslau-kavaliou approved these changes
Looking good

2023-06-28 09:38 UTC, merged